/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gguo.trackingguru;

import java.awt.Toolkit;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author gguo
 */
public class AddTracking extends javax.swing.JFrame {

    /**
     * Creates new form APISettingFrame
     */
    private Tracking mainTracking;

    //private String XMLFilePath;
    public AddTracking(Tracking tracking) {
        initComponents();
        this.mainTracking = tracking;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtf_tn = new javax.swing.JTextField();
        jbtn_cancel = new javax.swing.JButton();
        jbtn_save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtf_name = new javax.swing.JTextField();
        warning_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adding Tracking");
        setResizable(false);

        jLabel1.setText("Tracking Number:");

        jbtn_cancel.setText("Cancel");
        jbtn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelActionPerformed(evt);
            }
        });

        jbtn_save.setText("Save");
        jbtn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_saveActionPerformed(evt);
            }
        });

        jLabel2.setText("Name:");

        warning_label.setForeground(new java.awt.Color(255, 0, 0));
        warning_label.setPreferredSize(new java.awt.Dimension(70, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn_cancel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf_tn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtn_save)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(warning_label, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtf_tn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(warning_label, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_cancel)
                    .addComponent(jbtn_save))
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-322)/2, (screenSize.height-184)/2, 322, 184);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); //you can't see me!
        this.dispose();
    }//GEN-LAST:event_jbtn_cancelActionPerformed

    private void jbtn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_saveActionPerformed
        String tn = jtf_tn.getText();
        String name = jtf_name.getText();
        DefaultListModel listModel = mainTracking.getTracking_listModel();
        JList list = mainTracking.getTracking_list();
        //User didn't type in a unique name...
        if (tn.equals("") || alreadyInList(listModel, tn)) {
            Toolkit.getDefaultToolkit().beep();
            jtf_tn.requestFocusInWindow();
            jtf_tn.selectAll();
            warning_label.setText("Tracking number can not be empty or repeated...");
            return;
        }


        int index = list.getSelectedIndex(); //get selected index
        if (index == -1) { //no selection, so insert at beginning
            index = 0;
        } else {           //add after the selected item
            index++;
        }

        listModel.insertElementAt(tn, index);
        warning_label.setText("");

        //add props
        ComponentControls.AddNewProperty(tn, name, mainTracking.getCurrentTabName());
        

        //Reset the text field.
        jtf_tn.requestFocusInWindow();
        jtf_tn.setText("");
        jtf_name.setText("");


        //Select the new item and make it visible.
        list.setSelectedIndex(index);
        list.ensureIndexIsVisible(index);

    }//GEN-LAST:event_jbtn_saveActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtn_cancel;
    private javax.swing.JButton jbtn_save;
    private javax.swing.JTextField jtf_name;
    private javax.swing.JTextField jtf_tn;
    private javax.swing.JLabel warning_label;
    // End of variables declaration//GEN-END:variables

    protected boolean alreadyInList(DefaultListModel list, String name) {
        return list.contains(name);
    }
}
